### PR TITLE
Feature/#5 random map selection

### LINKED ISSUE #5: Introduce button to randomise map selection
Helps to see other maps that the most common ones during the strategy implementation.
Avoids that a strategy is optimized only for one map.

### PR DESCRIPTION
**Pull request by tommy33790**
- Added button "Zufällig" into the panel for level selection to randomly select a level
- The randomly selected level will never be the one currently selected except <2 levels are loaded
- Given meaningful names to all `jButton`, `jPanel` and `jLabel` in `ConfigurationPanel`

grafik

### CODE REVIEW

**Review by DivineThreepwood — DISMISSED** [review]
nice 👍

**Review by DivineThreepwood — CHANGES_REQUESTED** [review]
Code itself is fine, however your random selection will cause an out of bound exception in case the last maps has been selected and the random value selects the last map as well. 

You could fix this by using a modulo operator that takes care of not running out of bounds.

**Comment by tommy33790** [comment]
> Code itself is fine, however your random selection will cause an out of bound exception in case the last maps has been selected and the random value selects the last map as well.
> 
> You could fix this by using a modulo operator that takes care of not running out of bounds.

I appreciate you bringing this up, but after a second look at the code in the function `RandomGenerator.getRandom(min,max)` I think it's safe to say that it's only the case if the `ConfigurationPanel.levelChooserComboBox` is modified while the function `ConfigurationPanelrandomLevelButtonActionPerformed()` runs.
Is this the case you're expecting an OutOfBoundsException?


Here is an annotated version of the function `ConfigurationPanelrandomLevelButtonActionPerformed()`:
```kotlin
private fun randomLevelButtonActionPerformed() {
        val maxIndex = levelChooserComboBox!!.itemCount - 1
        // here maxIndex <= n-1
        if (maxIndex < 1) { // return if the randomisation wouldn't make any sense
            return
        }

        var nextLevelIndex = RandomGenerator.getRandom(0, maxIndex) // getRandom is min inclusive and max exclusive (as Math.random() results in 0 <= x < 1)
        // here nextLevelIndex < maxIndex
        // therefore nextLevelIndex <= n-2
        if (nextLevelIndex >= levelChooserComboBox!!.selectedIndex) {
            nextLevelIndex += 1
        }
        // here nextLevelIndex <= n-1
        // therefore nextLevelIndex <= maxIndex (which is the max allowed index, hence the name)
        levelChooserComboBox!!.selectedIndex = nextLevelIndex
    }
```


Example where n=30
```kotlin
private fun randomLevelButtonActionPerformed() {
        val maxIndex = levelChooserComboBox!!.itemCount - 1
        // here maxIndex = 29
        if (maxIndex < 1) { // 29 < 1 is false
            return
        }

        var nextLevelIndex = RandomGenerator.getRandom(0, maxIndex)
        // here nextLevelIndex = 28 (because getRandom is max exclusive)

        // in the two worst cases:
        // with selectedIndex = 29 the following if is false
        // with selectedIndex = 28 the following if is true
        if (nextLevelIndex >= levelChooserComboBox!!.selectedIndex) {
            nextLevelIndex += 1
        }
        // in both worst cases nextLevelIndex = 29
        // if we can assume that the combo box hasn't been modified this is valid as 0 <= 29 < 30
        levelChooserComboBox!!.selectedIndex = nextLevelIndex
    }
```

Example where n=2
```kotlin
private fun randomLevelButtonActionPerformed() {
        val maxIndex = levelChooserComboBox!!.itemCount - 1
        // here maxIndex = 1
        if (maxIndex < 1) { // 1 < 1 is false
            return
        }

        var nextLevelIndex = RandomGenerator.getRandom(0, maxIndex)
        // here nextLevelIndex = 0 (because getRandom is max exclusive)

        // in the two cases:
        // with selectedIndex = 1 the following if is false
        // with selectedIndex = 0 the following if is true
        if (nextLevelIndex >= levelChooserComboBox!!.selectedIndex) {
            nextLevelIndex += 1
        }
        // here nextLevelIndex = 0 or 1
        // in both cases nextLevelIndex != selectedIndex
        // in both cases this is valid as 0 <= nextLevelIndex <= 1
        levelChooserComboBox!!.selectedIndex = nextLevelIndex
    }
```

**Comment by DivineThreepwood** [comment]
Okay, you are right, index out of bounds is therefore not possible. 
However, this code is way to complex to understand with all its exception.
Especially `if (nextLevelIndex >= levelChooserComboBox!!.selectedIndex) {` would lead to a situation were you never select the next map that is listed right after currently selected one. Is this intended?

**Comment by DivineThreepwood** [comment]
Anyway, the RandomGenerator is the main Problem here and we should mark it as deprecated since kotlin provides some nice alternatives. How about this simplified version?
```
private fun randomLevelButtonActionPerformed() =
        levelChooserComboBox
            ?.takeIf { it.itemCount > 1 }
            ?.selectedIndex.let { selectedIndex ->
                do {
                    levelChooserComboBox!!.selectedIndex = Random.nextInt(levelChooserComboBox!!.itemCount)
                } while (selectedIndex == levelChooserComboBox!!.selectedIndex)
            }
```

**Review by DivineThreepwood — APPROVED** [review]

**Pull request merged**
